export const CUSTOMIZATION_SHOW = "CUSTOMIZATION_SHOW"
export const CUSTOMIZATION_COLORS_UPDATE = "CUSTOMIZATION_COLORS_UPDATE"
export const CUSTOMIZATION_LOGO_UPDATE = "CUSTOMIZATION_LOGO_UPDATE"
export const CUSTOMIZATION_LANG_UPDATE = "CUSTOMIZATION_LANG_UPDATE"